Support (de)serialize a subclass of primitive type
Now pyserde supports a class

```
class Str(str):
    pass
```

NOTE:
Some serialize APIs e.g to_yaml doesn't support subclasses of
primitive types. You will get an exception like below

```
yaml.representer.RepresenterError: ('cannot represent an object', 'a')
```